# Generated by Django 5.0.1 on 2024-02-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='categoria',
        ),
    ]
