# Generated by Django 5.0.1 on 2024-02-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0003_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
