# Generated by Django 5.0.1 on 2024-02-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0005_usuario_carrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Carritos',
        ),
    ]
