# Generated by Django 5.0.1 on 2024-02-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0006_rename_carrito_carritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carritos',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
