# Generated by Django 5.0.1 on 2024-02-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0007_remove_usuario_user_delete_carritos_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
