# Generated by Django 5.0.1 on 2024-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0010_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='juego_favorito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lugar_residencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='plataforma_favorita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ventas_compradas',
            field=models.IntegerField(default=0),
        ),
    ]
