# Generated by Django 5.0.1 on 2024-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0011_perfilusuario_edad_perfilusuario_juego_favorito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
