# Generated by Django 5.0.1 on 2024-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0012_perfilusuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
