# Generated by Django 5.0.1 on 2024-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0015_remove_ordenes_nombre_ordenes_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='coaccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coaventura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codeportivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coestrategia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='conintendo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coplataforma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coplay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='corol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coterror',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='coxbox',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
