# Generated by Django 5.0.1 on 2024-03-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0016_perfilusuario_coaccion_perfilusuario_coaventura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
