# Generated by Django 5.0.1 on 2024-03-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0018_alter_perfilusuario_coxbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='coaccion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='coaventura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='codeportivo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='coestrategia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='conintendo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='coplataforma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='coplay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='corol',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='coterror',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
