# Generated by Django 5.0.1 on 2024-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0019_alter_perfilusuario_coaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='comusicales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
