# Generated by Django 5.0.1 on 2024-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccom', '0020_perfilusuario_comusicales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='ventas_compradas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
